### ISSUE TITLE
Move PDF source code to new repository

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-pdf#10]
## Description
Move source code from altinn-studio repository

https://ao.ms/how-to-split-a-subdirectory-to-a-new-git-repository-and-keep-the-history/

If changes exist on main branch in new repository use:
```cmd
git pull origin main --allow-unrelated-histories
```

Must merge directly into main to keep history, pr with squash all commits

## Acceptance criteria
Source code is deleted from Altinn-studio repository

## Development tasks
- [ ] Move source code to new repository
	- Follow instructions here:  https://ao.ms/how-to-split-a-subdirectory-to-a-new-git-repository-and-keep-the-history/
	- Move code to root
    - Work on a branch that is not main in order to create a PR with the changes. 
    - Do NOT merge the PR, once approved, rather merge directly into main to keep commit history
- [ ] Restructure repository
- [ ] Set up new SonarCloud project
- [ ] Move relevant pipelines to GitHub actions
	- [ ] CodeQL (Replaces LGTM)
	- [ ] Test & analysis for internal 
	- [ ] Test & analysis for fork PR
- [ ] QA
- [ ] Update all remaining pipelines in AzDo to go towards the new repository
  - [ ] Disable and delete XXX-pull-request pipeline
  - [ ] Disable and delete analysis pipeline
  - [ ] Change repository for XXX-master pipeline. Update path for dockerfile and build context
  - [ ] Update release pipeline, trigger of K6 test should not use same source branch
- [ ] Set up README.md for new repository
- [ ] Delete source code from altinn-studio repository.
- [ ] Delete outdated sonarcloud project

## Test
- [ ] Regression test build/deploy/analysis of compontent

**Comment by ivarne** [comment]
- [ ] Update `altinn-studio/src/development/docker-compose.yml` to reference pdf image on dockerhub (or acr?), and document how to run pdf with local changes.

**Comment by acn-sbuad** [comment]
Obsolete. New pdf generator is deployed. So source code in this repo
