### ISSUE TITLE
Variables in text referencing data in applicationSettings or instanceContext does not work in pdf

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#14]
## Description

Variables in text can reference either the data model, application settings or an instance context (see relevant [pull request](https://github.com/Altinn/altinn-studio/pull/7776)):

```typescript
    const dataSources: IDataSources = { 
      dataModel: formData, 
      applicationSettings:  applicationSettings, 
      instanceContext: instanceContext
    };
```

Currently, this is not supported in the pdf generator as dataModel is the only source implemented.

## How to
1. Create an app with texts that reference variables in either instance context or application settings
2. See that texts works fine in app frontend but not in pdf.

**Comment by SandGrainOne** [comment]
All PDF content related features are now outside the scope of the PDF-generator. The PDF-generator will be built to generate PDF from HTML produced by the Apps. 

Extremely important bug fixes might be considered. This issue is old and stale.
