### ISSUE TITLE
PDF generator shows empty values for rep groups where group name is used for child item

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-pdf#2]
@lorang92 commented on [Tue Nov 02 2021](https://github.com/Altinn/altinn-studio/issues/7324)

## Describe the bug
See title.

Related line: `String replacedBinding = currentBinding.replace(groupBinding, groupBinding + '[' + groupIndex + ']');`
Investigate if we similar other faulty logic.

## To Reproduce
1. Create a service that has a rep group with a child property that matches group name
2. Submit form with group
3. See that only first value is shown

## Expected behavior
Nothing wrong with supporting children with name or partial name as parent, this should be supported.

## Additional info
Example xsd:
```
  <owner>
    <ownerorganisationid>1</ownerorganisationid>
    <ownername>a</ownername>
  </owner>
  <owner>
    <ownerorganisationid>2</ownerorganisationid>
    <ownername>b</ownername>
  </owner>
  <owner>
    <ownerorganisationid>3</ownerorganisationid>
    <ownername>c</ownername>
  </owner>
```

Output:
![image](https://user-images.githubusercontent.com/10416981/139838971-67416150-c715-4e92-8587-95b2d03c7b02.png)

**Comment by acn-sbuad** [comment]
Regression test completed and bugfix verified n AT ![image.png](https://images.zenhubusercontent.com/5c8f655333fd990b927f5ea1/28d7cada-20c6-4208-ae19-a5e4a69ba217)
