### ISSUE TITLE
Add support for Summary component in PDF

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#23]
## Description
See title.

## Acceptance criteria
- PDF generation supports summary component

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
- [ ] Add support for summary in pdf

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by SandGrainOne** [comment]
All PDF content related features are now outside the scope of the PDF-generator. The PDF-generator will be built to generate PDF from HTML produced by the Apps.
