### ISSUE TITLE
PDF displays same font-size for all headers

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#25]
## Describe the bug
Generated PDF does not differantiate header types in the presentation.

## To Reproduce
1. Add different types of headers
2. Generate PDF
3. See issue

## Expected behavior
We should differantiate header types.

## Screenshots

![image](https://user-images.githubusercontent.com/10416981/141073914-fd86e889-4dcd-4506-ba71-bbab6034572b.png)

**Comment by SandGrainOne** [comment]
All PDF content related features are now outside the scope of the PDF-generator. The PDF-generator will be built to generate PDF from HTML produced by the Apps. 

Extremely important bug fixes might be considered. This issue is old and stale.
