### ISSUE TITLE
Support horizontally aligned components in PDF

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#27]
## Description
Horizontally aligned components were implemented for app-frontend in Altinn/altinn-studio#1515. This is not something we currently support in our generated PDF. Is this something we should support? 

## Considerations
- How is this technically feasible? Investigate if there exist any libraries to aid with this for PDFBox.

## Specification tasks

- [ ] Development tasks are defined

## Development tasks
> Add tasks here

## Test
> Add test cases here as checkboxes that are being tested as part of the changes.

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by SandGrainOne** [comment]
All PDF content related features are now outside the scope of the PDF-generator. The PDF-generator will be built to generate PDF from HTML produced by the Apps.
