### ISSUE TITLE
Upgrade pdf for repeating groups

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#28]
## Description
Making pdf work for repeating groups is handled in Altinn/altinn-studio#4572, but we should look into the design in the pdf for repeating groups.

Currently, all components that are part of a repeating group is just listed out with no clear indication that they are part of a group and are rendered in the same manner as all other components.

Do we need to change this design?

## Acceptance criteria
- A design for repeating groups in pdf is specified 
- The design is implemented in the pdf generator

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by SandGrainOne** [comment]
All PDF content related features are now outside the scope of the PDF-generator. The PDF-generator will be built to generate PDF from HTML produced by the Apps. 

Extremely important bug fixes might be considered. This issue is old and stale.
