### ISSUE TITLE
Markdown is not supported in PDF

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#29]
## Describe the bug
Markdown is not supported in PDF making texts that use markdown-formatting look weird.

## To Reproduce
1. Add markdown to texts in an app
2. Generate PDF
3. See weird formatting.

## Expected behavior
Ideally, we should support markdown for PDF. Are there other alternatives here?

## Screenshots
![image](https://user-images.githubusercontent.com/10416981/96243531-27ff5f00-0fa5-11eb-9739-bb9ecf1d8697.png)

**Comment by lvbachmann** [comment]
To be solved together with other PDF issues.

**Comment by xmrsa** [comment]
I was rather shocked when I saw my pdf in the archive in TT02. It obviously doesn't understand html or markdown: 
![image](https://user-images.githubusercontent.com/42466346/154044381-a1e6d55f-0f37-4ecb-927d-8b6cab7e2a52.png)
It is impossible to make a form so simple that it doesn't need any formatting to be readable. You have to fix this.

**Comment by SandGrainOne** [comment]
This is out of scope for the PDF generator. Markdown is already supported by the Apps responsible for generating the content of the PDF.
