### ISSUE TITLE
Non repeating group is not rendered in pdf

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-pdf#3]
@lorang92 commented on [Wed May 26 2021](https://github.com/Altinn/altinn-studio/issues/6335)

## Describe the bug
Groups that are non repeating does not get rendered in PDF. 

## To Reproduce
1. Add a non repeating group with some child components to an app (
2. Submit the app
3. See that the genereated PDF does not include the group

## Expected behavior
Should render the groups child components as it does with repeating groups.

## Additional info
> Add any other relevant context info about the problem here.
> For example OS (Windows, MacOS, iOS), browser (Chrome, Firefox, Safari), device (iPhone, laptop), screen-size, etc.

---

@elenagustafsson commented on [Thu Mar 03 2022](https://github.com/Altinn/altinn-studio/issues/6335#issuecomment-1057975881)

Når er det den er planlagt rettet? Flere av våre skjema skal i arkivsystem i mottaket som pdf, hvis ikke noen vises i pdf, så er skjema ubrukelig for oss.

---

@lorang92 commented on [Thu Mar 03 2022](https://github.com/Altinn/altinn-studio/issues/6335#issuecomment-1057982677)

@elenagustafsson dette ligger inne i sprint og blir forhåpentligvis løst inneværende sprint.

**Comment by acn-sbuad** [comment]
Fix verified. Bug #9 created, seems to be an unrelated issue
