### ISSUE TITLE
Add support for image component in PDF-generator

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#30]
## Description
In Altinn/altinn-studio#379 we added support for an image component. We should also support this in our pdf-generator.

## Acceptance criteria
- PDF generator handles images

## Specification tasks

- [ ] Respect alignment?
- [ ] Display image possible? What do we support? Any limitations?

## Development tasks
- [ ] Add support for image component

## Test
> Add test cases here as checkboxes that are being tested as part of the changes.

## Definition of done
Verify that this issue meets [DoD](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049246/Definition+of+Done) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by SandGrainOne** [comment]
All PDF content related features are now outside the scope of the PDF-generator. The PDF-generator will be built to generate PDF from HTML produced by the Apps.
