### ISSUE TITLE
PDF-generator should return charset in Content-Type header

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#31]
## Describe the bug
The charset should be included in the defined content-type. Investigate if `UTF-8` can be used here instead of `ISO 8859-1`

` response.addHeader("Content-Type", "application/pdf");`

## To Reproduce
1. Generate a pdf
2. See that the response does not include charset

## Expected behavior
Should include charset in content-type.

## Tasks

- [x] Just check the content-type of the response from the new pdf generator.

## Analysis

Tested with a curl directly from the pdf-generator pod. 
```
curl -v --location 'http://pdf-generator.pdf.svc.cluster.local/pdf' \
--header 'Content-Type: application/json' \
--data '        {
            "url" : "https://vg.no",
            "waitFor": 5000
        }'
```

Charset not included in response header from new pdf generator. 

```
< HTTP/1.1 200 OK
< x-powered-by: Express
< content-type: application/pdf
< x-response-url: https://vg.no
< x-response-code: 200
< x-response-ip: 51.120.51.18
< x-response-port: 443
< date: Tue, 14 Feb 2023 13:57:39 GMT
< content-length: 23021
<
```

**Comment by SandGrainOne** [comment]
We should verify that the new PDF generator does this correctly.

**Comment by acn-sbuad** [comment]
Char set not included in response headers for new pdf generator.

**Comment by ivarne** [comment]
Pdf is a binary format and declares its own charset internally. I don't think it is correct to add charset to `application/pdf`. Charset is only used for text formats that don't have metadata about charset in the file itself.

**Comment by altinnadmin** [comment]
Agree with @ivarne. This is a buggy bug that should be closed.

https://stackoverflow.com/questions/23163089/what-is-the-correct-charset-for-a-application-pdf-content-type-http-response-hea
