### ISSUE TITLE
Dynamics in repeating groups not handled in PDF

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-pdf#4]
@ingunnjv commented on [Wed Feb 02 2022](https://github.com/Altinn/altinn-studio/issues/7942)

## What needs to be solved?

When a form has repeating groups with dynamics in them, I would like to reproduce the dynamics in the PDF by excluding different components in different entries in the repeating group.

I have a form with many repeating groups, where each group contains its own dynamics. Example:
![image](https://user-images.githubusercontent.com/25951311/152142055-83ab670b-d148-4302-9932-dc954957d4c3.png)

If "Annet" is chosen, a textbox appears where user can fill in a description:
![image](https://user-images.githubusercontent.com/25951311/152141086-8b56632b-44b5-4eb7-9cc2-fdaa18964293.png)

In the PDF, I did not find a way to implement this. So the component for "Beskrivelse av annet format" is always visible even if "Annet" is not chosen:
![image](https://user-images.githubusercontent.com/25951311/152141553-4182876d-cfa2-43bb-b782-011412af4ae2.png)

## How do you want it solved?

I want to configure this in PdfHandler. Perhaps we could add a "{0}" to the string of components in repeating groups, similarly to how it is handled in RuleConfiguration. Would also need a way to access indices of the field which triggers dynamics.

## Alternative solutions
It is already possible to loop through entries in a repeating group in PdfHandler since it is a list, so a possible solution is to add functionality for passing an index to layoutSettings.Components.excludeFromPdf. For example by adding an index to the component name string.
This leaves more work for the developer of the app.

**Comment by acn-sbuad** [comment]
This is already supported. Documented syntax on docs.altinn.studio.
