### ISSUE TITLE
Update the scripts for initial creation of a new cluster to include deploy of PDF-generator

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-pdf#52]
## Description

Automated deploy for pdf-generator for apps cluster was completed in #43.

We want the pdf-generator to be set up on creation of new apps cluster. 
Scripts for creation should be adjusted to include this. 

```                    
helm repo add altinn-charts https://charts.altinn.studio
helm repo update
helm install --namespace pdf --set environment=$(Environment) pdf-generator pdf-generator --create-namespace        
```

## Acceptance criteria
- [ ] new apps clusters contain a pdf-generator deployment

**Comment by bengtfredh** [comment]
We add deploy to terraform for create cluster:
```hcl
resource "helm_release" "pdf_generator" {
  name             = "pdf-generator"
  namespace        = "pdf"
  repository       = "https://charts.altinn.studio"
  chart            = "pdf-generator"
  create_namespace = true
}
```
Note: Leave version blank. Terraform will pick latest version on install, but will not try to upgrade as long as version is not set.  

Tasks:
- [x] Add code to iac for apps cluster
- [x] Import already deployed pdf-generator to state
- [x] Verify Terraform accept upgrade to newer version from other pipeline

**Comment by bengtfredh** [comment]
pdf-generator get deployed on cluster create.
