### ISSUE TITLE
Pdf service crashes if layout component is missing textResourceBindings

### ISSUE THREAD

**Issue by tjololo** [Altinn/altinn-pdf#54]
### Description of the bug

If a layout component eg. Input or any other component is missing textResourceBindings PDF-service fails to generate PDF and returns 500

### Steps To Reproduce

Create a app with a layout like this:
```
{
  "$schema": "https://altinncdn.no/schemas/json/layout/layout.schema.v1.json",
  "data": {
    "layout": [
      {
        "id": "30558946-9d1d-4a49-898c-79d94b858e01",
        "type": "Input",
        "dataModelBindings": {
          "simpleBinding": "melding.name"
        },
        "required": true,
        "readOnly": false
      }
    ]
  }
}
```

Deploy app and see PDF service return http 500 response due to textResourceBindings being null.

**Comment by FinnurO** [comment]
Should be caught in app validation in Studio or deploy checks? Completness and consistency checks?

**Comment by tjololo** [comment]
Slack discussion: https://altinn.slack.com/archives/C02FK32SFA4/p1669189333588629

**Comment by tjololo** [comment]
Workaround, add empty textresourcebindings:
```diff
{
  "$schema": "https://altinncdn.no/schemas/json/layout/layout.schema.v1.json",
  "data": {
    "layout": [
      {
        "id": "30558946-9d1d-4a49-898c-79d94b858e01",
        "type": "Input",
        "dataModelBindings": {
          "simpleBinding": "melding.name"
        },
+       "textResourceBindings": {},
        "required": true,
        "readOnly": false
      }
    ]
  }
}
```

**Comment by SandGrainOne** [comment]
Workaround good enough for now. New PDF generator will not have this issue.
