### ISSUE TITLE
Task `Trigger verification of deployed version` in release pipeline fails

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-pdf#62]
## Description
Task fails consistently for Platform PDF & Register to production consistently.
Runs green for other components e.g. Storage and events

## To Reproduce
1. Trigger deploy of a pending or existing release of Platform PDF to prod
2. See error

## Expected behavior
Task should trigger successfully.

**Comment by annerisbakk** [comment]
@acn-sbuad Er denne fremdeles aktuell?

**Comment by SandGrainOne** [comment]
Old, outdated.
