### ISSUE TITLE
Failing pdf pod not resulting in any alerts

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-pdf#65]
Related to patching of Azure identity (see #64 ). Pod did not start.

Expected outcome:
- If the alert did not fire; a working trigger
- If the alert did fire; update to "repeating alert" - make assesment if there is too much noise.

**Comment by acn-sbuad** [comment]
Alert rule has been adjusted in collaboration with @simon-ellefsen.  A looser definition of how many times a pod needs to fail before we are alerted. WIll be rolled out asap. In future it might be wise to look at an alert triggering based on the restart count of a singular pod.

**Comment by acn-sbuad** [comment]
Alert rule has been adjusted in collaboration with @simon-ellefsen. A looser definition of how many times a pod needs to fail before we are alerted. In future it might be wise to look at an alert triggering based on the restart count of a singular pod.
