### ISSUE TITLE
Data model bindings is case-sensitive in PDF generation, but insensitive in other cases

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-pdf#7]
Bug originally created by @simendsjo [Wed Mar 02 2022](https://github.com/Altinn/altinn-studio/issues/8146)

## Description
For a datamodel, `a`, using `A` in the databinding FormLayout works fine, while the field turns up blank in PDF generation.

## Analysis
Created a minimal example of a form where input field no 2 has a different casing than the datamodel.
Test shows that although PDF is case sensitive, so is app frontend. 

## Screenshots
![bug-7.gif](https://images.zenhubusercontent.com/5c8f655333fd990b927f5ea1/f5b7a1d5-e333-4b66-8e90-55ccac1640f2)

**Comment by acn-sbuad** [comment]
As case sensitivity is not isolated to PDF but something we find multiple places in our solution I am closing the bug. If case insensitivity is required a feature request should be created. Will require both changes in app frontend and PDF generation.
