### ISSUE TITLE
Formdata field not rendered in PDF

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-pdf#9]
## Description
During testing of #3 a new bug was found. 
Components are rendered in the pdf, but the formdata is not included. 
For the given value in the datamodel, the value is never shown regardless of component type or whether or not the component is placed within a non-repeating group. 

## To Reproduce
1. Go to dev.altinn.studio
2. Deploy ttd/bug-3 to preferred test environment
3. Fill out form data
4. Submit form
5. Inspect pdf

6. See error	

## Expected behavior
All form data submitted should be visible in the pdf. 

## Screenshots
[bug-3 (3).pdf](https://github.com/Altinn/altinn-pdf/files/8316917/bug-3.3.pdf)

**Comment by SandGrainOne** [comment]
This issue is stale and priorities dictates that this will not be worked on.
